sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - axel
    - cpanminus
    - libluajit-5.1-dev

cache:
  apt: true
  directories:
  - download-cache

env:
  global:
    - NGINX_VERSION=1.9.15
    - JOBS=3
    - TEST_NGINX_SLEEP=0.006
    - LUA_DEV=libluajit-5.1-dev LUA_INCLUDE_DIR=/usr/include/luajit-2.0 LUALIB=-lluajit-5.1
  matrix:
    - NGINX_VERSION=1.9.15
    - NGINX_VERSION=1.11.2

install:
    - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
    - git clone https://github.com/openresty/openresty.git ../openresty
    - git clone https://github.com/openresty/lua-cjson.git
    - git clone https://github.com/openresty/lua-nginx-module.git ../lua-nginx-module
    - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx
    - git clone https://github.com/openresty/nginx-devel-utils.git

script:
  - cd lua-cjson && make -j$JOBS && sudo make install && cd ..
  - export PATH=$PWD/work/nginx/sbin:$PWD/nginx-devel-utils:$PATH
  - ngx-build $NGINX_VERSION --with-debug --with-cc-opt="-DDEBUG_MALLOC" --with-ipv6 --add-module=../lua-nginx-module  > build.log 2>&1 || (cat build.log && exit 1)
  - prove -r t
